blank_issues_enabled: false
contact_links:
  - name: ACT Rules Community Group
    url: https://github.com/act-rules/act-rules.github.io/discussions
    about: Please ask here first if you are not sure which template you should use