# This workflow runs when:
# - A push lands on develop branch
# - It notifies the website repo with a repository_dispatch event (this event starts a new website build)
name: dispatch

on:
  push:
    branches:
      - develop

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - run: |
          curl -XPOST -u "${{ secrets.USER_NAME }}:${{ secrets.USER_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/act-rules/act-rules-web/dispatches --data '{ "event_type": "build_application" }'
