name: PR Preview
on:
  pull_request: {}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      branch_name: ${{ github.event.pull_request.head.ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Configure git
        run: |
          git config --global url."https://daniel-montalvo/wcag-act-rules:${{ secrets.PAT_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.name "daniel-montalvo"
          git config --global user.email "users.noreply@github.com"
      - name: Build and deploy WAI update
        run: npm run pr:preview
      - name: Comment on PR with preview link
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Preview ready at https://deploy-preview-${branch_name}--wai-wcag-act-rules.netlify.app"
