name: PR Preview
on:
  pull_request: {}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Configure git
        run: |
          git config --global user.name "daniel-montalvo"
          git config --global user.email "users.noreply.github.com"
      - name: Build and deploy WAI update
        env:
          branch_name: ${{ github.event.pull_request.head.ref }}
        run: npm run pr:preview
