# This workflow runs when a commit lands in develop
name: wai-deploy
on:
  push:
    branches:
      - develop

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - name: Install dependencies
        run: npm ci
      - name: Configure git
        run: |
          git config --global url."https://${{ secrets.WAI_GIT_NAME }}:${{ secrets.WAI_GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.name "${{ secrets.WAI_GIT_NAME }}"
          git config --global user.email "${{ secrets.WAI_GIT_EMAIL }}"
      - name: Build and deploy WAI update
        run: npm run build:wai
