# This workflow runs when a commit lands in develop
name: wai-deploy
on:
  push:
    branches:
      - develop-test

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Git setup
      - run: git config --global url."https://${{ secrets.WAI_GIT_NAME }}:${{ secrets.WAI_GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - run: git config --global user.name "${{ secrets.WAI_GIT_NAME }}"
      - run: git config --global user.email "${{ secrets.WAI_GIT_EMAIL }}"

      - run: npm install
      - run: npm run build:wai
